const CHANGE_STATS = 'CHANGE_STATS';
const CHANGE_LOGS = 'CHANGE_LOGS';
const CHANGE_CONTAINERS = 'CHANGE_CONTAINERS';
const CHANGE_CURRENT_CONTAINER = 'CHANGE_CURRENT_CONTAINER';

export {
  CHANGE_STATS,
  CHANGE_LOGS,
  CHANGE_CONTAINERS,
  CHANGE_CURRENT_CONTAINER,
};
